name: Connect to GCE Instance

on:
  push:
    branches:
      - main

jobs:
  connect-to-gce:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: SSH into GCE instance
        uses: appleboy/ssh-action@master
        with:
          host: 34.73.29.135  # Replace with your GCE instance IP address
          username: rockysinghearthday  # Replace with your GCE instance username
          key: ${{ secrets.GCE_SSH_PRIVATE_KEY }}
          script: |
            # Now you are connected to the GCE instance via SSH.
            # You can execute commands or run scripts here.
            ls -al  # Example command to list files in the home directory
